spring:
  redis:
    host: localhost
    port: 6379
    database: 3
    password: root
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static/,classpath:/public/,classpath:/upload/,file:./upload/
  datasource:
      url: jdbc:mysql://192.168.1.3/meeting_customized?useUnicode=true&characterEncoding=utf-8
      username: root
      password:
