spring:
  application:
    name: test
  profiles:
    active: dev
  http:
    encoding:
      force: true
  thymeleaf:
    cache: false
    mode: HTML5
  ##静态资源处理方式
  resources:
    chain:
      cache: true
      strategy:
        content:
          enabled: true
          paths: /**
  ##数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      connect-properties: config.decrypt=true
      filter:
        config:
          enabled: true
      connection-init-sqls: set names utf8mb4;
      initial-size: 2
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      async-init: true
  ##redis相关
  redis:
    jedis:
      pool:
        max-active: 500
        ##连接池的最大等待时间（-1表示无限制）
        max-wait: -1
        ##连接池中的最大空闲连接
        max-idle: 100
        ##连接池中的最小空闲连接
        min-idle: 50
      ##连接超时时间
      time-out: 10000
  servlet:
    multipart:
      #$上传一个文件最大值,默认1Mb
      max-file-size: 200MB
      ##上传多个文件最大值,默认10Mb
      max-request-size: 200MB
mybatis:
#  ##mybatis mapper文件路径
  mapper-locations: mapper/*.xml
server:
  servlet:
    session:
      ##解决静态url带jsessionid问题
      tracking-modes: cookie
ranking:
  limit: 100
file:
  tmp:
    save_path: /tmp #转存tomcat临时文件路径
